<a href="https://colab.research.google.com/github/quete-importa/Inteligencia-Artificial-IA/blob/main/tarea_Domingo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#numero 1 version de python
import numpy as np

print(np.__version__)


1.25.2


In [ ]:
#numero 2 numeros del 0 al 9
import numpy as np

arr = np.arange(10)

print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#numero 3 crear numero de diez digitos y cambiar el mayor por 0
import numpy as np


vector = np.random.rand(10)


print("Vector original:", vector)


max = np.argmax(vector)


vector[max] = 0


print("Vector modificado:", vector)


Vector original: [0.80650783 0.41942449 0.66373608 0.88581832 0.3563811  0.97822546
 0.22654828 0.97478799 0.9210354  0.43653968]
Vector modificado: [0.80650783 0.41942449 0.66373608 0.88581832 0.3563811  0.
 0.22654828 0.97478799 0.9210354  0.43653968]


In [ ]:
#numero 4 presenter el numero 8 de la siguiente Matriz
arr= np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])


numero_ocho = arr[1, 2]


print(numero_ocho)



8


In [ ]:
#numero 5 de los siguientes numeros presentar los numeros del 3 al 5
import numpy as np


arr = np.array([1, 2, 3, 4, 5, 6, 7])


subarray = arr[2:5]

print( subarray)


[3 4 5]


In [ ]:

# numero 6 presentar los ultimos 4 numeros
arr = np.array([1, 2, 3, 4, 5, 6, 7])

last_four = arr[-4:]


print(last_four)


[4 5 6 7]


In [ ]:
#numero 7 crear un arreglo de 3x3 y que todos sean true
import numpy as np

# Crear un arreglo 3x3 de todos True
arr_true = np.full((3, 3), True)

# Imprimir el resultado
print(arr_true)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# Numero 8 Extraer todos los números impares de arr
import numpy as np

# Definir el arreglo arr
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Crear una máscara booleana para los números impares
odd_mask = arr % 2 == 1

# Extraer los números impares usando la máscara
odd_numbers = arr[odd_mask]

# Imprimir el resultado
print("Números impares del arreglo:", odd_numbers)


Números impares del arreglo: [1 3 5 7 9]


In [ ]:
#Numero 9
import numpy as np

# Crear un vector con valores desde 10 hasta 49
vector = np.arange(10, 50)

# Imprimir el resultado
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#Numero 10 Invertir un vector (el primer elemento se convierte en el último)

import numpy as np

# Crear un vector de ejemplo
vector = np.arange(10, 50)

# Invertir el vector
vector_invertido = vector[::-1]

# Imprimir el resultado
print("Vector original:", vector)
print("Vector invertido:", vector_invertido)


Vector original: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Vector invertido: [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
# Numero 11 crear un arreglo 10x10 con valores enteros aleatorios y encontrar los valores mínimo y máximo

import numpy as np

# Crear un arreglo 10x10 con valores enteros aleatorios entre 0 y 100
arr = np.random.randint(0, 100, size=(10, 10))

# Encontrar el valor mínimo
min_value = np.min(arr)

# Encontrar el valor máximo
max_value = np.max(arr)

# Imprimir el arreglo, el valor mínimo y el valor máximo
print("Arreglo 10x10 con valores enteros aleatorios:")
print(arr)
print("Valor mínimo:", min_value)
print("Valor máximo:", max_value)


Arreglo 10x10 con valores enteros aleatorios:
[[15 22 96 96 53 50 74  3 82 86]
 [ 6 90 22 47 29 76 74  1 58 16]
 [41 72 40 69 43 85  0 77 99 49]
 [47 82  8  5 65 75  2 25 42 19]
 [27 12 91 83 10 60 96 41 13 54]
 [75 28 69 22 99 74 94 43 44 26]
 [41 56 23 97 76 70 64 75 62 55]
 [17 16 98 71 60 93 17 59 49 58]
 [49  0 29 39 81 17 58  8 53 51]
 [92 85 76 47 65 95  7  1 92  0]]
Valor mínimo: 0
Valor máximo: 99


In [ ]:
#Numero 12 crear un arreglo de 3x3x3 con valores aleatorios

import numpy as np

# Crear un arreglo 3x3x3 con valores aleatorios
arr = np.random.random((3, 3, 3))

# Imprimir el arreglo
print("Arreglo 3x3x3 con valores aleatorios:")
print(arr)


Arreglo 3x3x3 con valores aleatorios:
[[[0.90701299 0.97220894 0.68127611]
  [0.06291429 0.91724977 0.77483262]
  [0.63006599 0.33322795 0.39521085]]

 [[0.72229697 0.48063565 0.09219793]
  [0.73506537 0.95082524 0.372838  ]
  [0.09834023 0.36944799 0.06746242]]

 [[0.04532256 0.4298329  0.69100166]
  [0.71114529 0.35362441 0.99941384]
  [0.58569581 0.54288813 0.93105692]]]


In [ ]:
#Numero 13 reemplazar todos los números impares en arr con -1

import numpy as np

# Definir el arreglo arr
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Crear una copia del arreglo para mantener el original
arr_modified = arr.copy()

# Reemplazar los números impares con -1
arr_modified[arr_modified % 2 != 0] = -1

# Imprimir el arreglo modificado
print("Arreglo modificado con números impares reemplazados por -1:")
print(arr_modified)


Arreglo modificado con números impares reemplazados por -1:
[[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]]


In [ ]:
#Numero 14 crear un arreglo de tipo float

import numpy as np

# Crear un arreglo de tipo float
arr_float = np.array([1.0, 2.5, 3.7, 4.2, 5.9])

# Imprimir el arreglo y su tipo de dato
print("Arreglo de tipo float:", arr_float)
print("Tipo de dato del arreglo:", arr_float.dtype)


Arreglo de tipo float: [1.  2.5 3.7 4.2 5.9]
Tipo de dato del arreglo: float64


In [ ]:
#Numero 15 convertir un arreglo 1D a un arreglo 2D con 2 filas

import numpy as np

# Arreglo 1D de ejemplo
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Convertir a un arreglo 2D con 2 filas
arr_2d = np.reshape(arr_1d, (2, -1))

# Imprimir el arreglo original y el arreglo convertido
print("Arreglo 1D original:")
print(arr_1d)
print("Arreglo 2D con 2 filas:")
print(arr_2d)


Arreglo 1D original:
[1 2 3 4 5 6]
Arreglo 2D con 2 filas:
[[1 2 3]
 [4 5 6]]


In [ ]:
#numero 16 cómo encontrar los valores comunes entre dos arreglos

import numpy as np

# Definir dos arreglos aleatorios
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

# Encontrar los valores comunes entre Z1 y Z2
common_values = np.intersect1d(Z1, Z2)

# Imprimir los arreglos y los valores comunes
print("Primer arreglo Z1:")
print(Z1)
print("Segundo arreglo Z2:")
print(Z2)
print("Valores comunes entre Z1 y Z2:")
print(common_values)


Primer arreglo Z1:
[8 5 3 5 9 1 9 2 1 3]
Segundo arreglo Z2:
[3 3 8 4 7 1 7 0 9 6]
Valores comunes entre Z1 y Z2:
[1 3 8 9]


In [12]:
#Numero 17 considerar dos arreglos aleatorios A y B, verificar si son iguales

import numpy as np

# Definir dos arreglos aleatorios A y B
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

# Verificar si los arreglos A y B son iguales
are_equal = np.array_equal(A, B)

# Imprimir los arreglos y el resultado de la comparación
print("Arreglo A aleatorio:", A)
print("Arreglo B aleatorio:", B)
if are_equal:
    print("A y B son iguales.")
else:
    print("A y B no son iguales.")


Arreglo A aleatorio: [1 0 1 0 1]
Arreglo B aleatorio: [0 0 1 0 1]
A y B no son iguales.


In [13]:
#Numero 18 apilar los arreglos a y b verticalmente

import numpy as np

# Definir dos arreglos a y b
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

# Apilar a y b verticalmente
stacked = np.vstack((a, b))

# Imprimir el resultado
print("Arreglo apilado verticalmente:")
print(stacked)


Arreglo apilado verticalmente:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [14]:
#Numero 19 apilar los arreglos a y b horizontalmente

import numpy as np

# Definir dos arreglos a y b
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

# Apilar a y b horizontalmente
stacked = np.hstack((a, b))

# Imprimir el resultado
print("Arreglo apilado horizontalmente:")
print(stacked)


Arreglo apilado horizontalmente:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [15]:
#numero 20 obtener todos los elementos entre 5 y 10 del arreglo tmp
import numpy as np

# Definir el arreglo tmp
tmp = np.arange(15)

# Obtener los elementos entre 5 y 10 (inclusivos)
items_between_5_and_10 = tmp[(tmp >= 5) & (tmp <= 10)]

# Imprimir el resultado
print("Elementos entre 5 y 10 en el arreglo tmp:")
print(items_between_5_and_10)


Elementos entre 5 y 10 en el arreglo tmp:
[ 5  6  7  8  9 10]


In [16]:
#numero 21 cómo hacer una función en Python que maneje escalares para trabajar en arreglos de numpy

import numpy as np

def pair_max(a, b):
    """Obtener el máximo entre dos arreglos de numpy elemento por elemento"""
    return np.vectorize(max)(a, b)

# Ejemplo de uso
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

resultado = pair_max(a, b)
print(resultado)


[6 7 9 8 9 7 5]


In [17]:
#numero 22 intercambiar las columnas 1 y 2 en el arreglo arr

import numpy as np

# Definir el arreglo arr
arr = np.arange(9).reshape(3, 3)
print("Arreglo original:")
print(arr)

# Intercambiar las columnas 1 y 2
arr[:, [1, 2]] = arr[:, [2, 1]]

# Imprimir el resultado
print("Arreglo con columnas 1 y 2 intercambiadas:")
print(arr)


Arreglo original:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Arreglo con columnas 1 y 2 intercambiadas:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [18]:
#Numero 23 crear un arreglo 2D de forma 5x3 que contenga números decimales aleatorios entre 5 y 10

import numpy as np

# Crear un arreglo 2D de forma 5x3 con números decimales aleatorios entre 5 y 10
arr = np.random.uniform(5, 10, size=(5, 3))

# Imprimir el resultado
print("Arreglo 2D de forma 5x3 con números aleatorios entre 5 y 10:")
print(arr)


Arreglo 2D de forma 5x3 con números aleatorios entre 5 y 10:
[[8.45560436 9.531083   6.25717354]
 [9.37498171 8.4908614  7.30680599]
 [9.96588767 6.32184243 8.48987031]
 [9.89156636 7.14345077 5.85258629]
 [5.42728921 7.81066929 9.50376933]]
